### ISSUE TITLE
Friend's Username Capitalization

### ISSUE THREAD

**Issue by Lord0fBytes** [step-up-health/step-up-backend#1]
I love this app and I was just looking through some of the code. I noticed that you dont convert the friends username to lowercase. When searching for friends my phone will auto capitalize the first letter. It might be helpful to set it to lowercase when it searches the server like you do when you create a username.

**Comment by jneubrand** [comment]
thanks!

**Comment by jneubrand** [comment]
changes made and pushed in #5ee0b73, closing.
